-- Generated by `pnpm db:snapshot`. Do not edit by hand.
--
-- This is the schema the migrations add up to, checked in so a reviewer can
-- see the resulting shape rather than replaying every migration, and so CI
-- can fail when a migration lands without a regenerated snapshot.
--
-- schema version: 10

-- extensions

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- enum types

CREATE TYPE access_scope AS ENUM ('private', 'project', 'team', 'workspace', 'restricted');
CREATE TYPE actor_kind AS ENUM ('human', 'agent');
CREATE TYPE checkpoint_action AS ENUM ('created', 'updated', 'superseded', 'rejected');
CREATE TYPE checkpoint_trigger AS ENUM ('task_boundary', 'day_boundary', 'manual', 'pre_compaction');
CREATE TYPE conflict_resolution AS ENUM ('a_wins', 'b_wins', 'merged', 'both_retired');
CREATE TYPE item_kind AS ENUM ('decision', 'constraint', 'open_question', 'fact', 'artifact_ref');
CREATE TYPE item_status AS ENUM ('active', 'superseded', 'disputed', 'retired');
CREATE TYPE team_function AS ENUM ('engineering', 'product', 'design', 'sales', 'marketing', 'support', 'success', 'operations', 'finance', 'other');
CREATE TYPE team_role AS ENUM ('lead', 'member');

-- tables

CREATE TABLE actor (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  kind actor_kind NOT NULL,
  display_name text NOT NULL,
  external_ref text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE actor ADD CONSTRAINT actor_pkey PRIMARY KEY (id);
ALTER TABLE actor ADD CONSTRAINT actor_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE actor ADD CONSTRAINT actor_workspace_id_id_key UNIQUE (workspace_id, id);
CREATE UNIQUE INDEX actor_human_external_ref_unique ON public.actor USING btree (external_ref) WHERE ((external_ref IS NOT NULL) AND (kind = 'human'::actor_kind));
ALTER TABLE actor ENABLE ROW LEVEL SECURITY;
ALTER TABLE actor FORCE ROW LEVEL SECURITY;
CREATE POLICY actor_identity_lookup ON actor FOR SELECT USING (((kind = 'human'::actor_kind) AND (external_ref = NULLIF(current_setting('mneia.identity_subject'::text, true), ''::text)) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY actor_workspace_isolation ON actor USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE checkpoint (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  session_id uuid,
  actor_id uuid NOT NULL,
  trigger checkpoint_trigger NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  summary text
);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_pkey PRIMARY KEY (id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_session_id_fkey FOREIGN KEY (workspace_id, session_id) REFERENCES session(workspace_id, id);
CREATE INDEX checkpoint_workspace_id_project_id_created_at_idx ON public.checkpoint USING btree (workspace_id, project_id, created_at DESC);
CREATE INDEX checkpoint_workspace_id_session_id_idx ON public.checkpoint USING btree (workspace_id, session_id);
ALTER TABLE checkpoint ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint FORCE ROW LEVEL SECURITY;
CREATE POLICY checkpoint_workspace_isolation ON checkpoint USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE checkpoint_item (
  workspace_id uuid NOT NULL,
  checkpoint_id uuid NOT NULL,
  item_id uuid NOT NULL,
  action checkpoint_action NOT NULL
);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_pkey PRIMARY KEY (checkpoint_id, item_id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_checkpoint_id_fkey FOREIGN KEY (workspace_id, checkpoint_id) REFERENCES checkpoint(workspace_id, id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_item_id_fkey FOREIGN KEY (workspace_id, item_id) REFERENCES context_item(workspace_id, id);
CREATE INDEX checkpoint_item_item_id_idx ON public.checkpoint_item USING btree (item_id);
ALTER TABLE checkpoint_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint_item FORCE ROW LEVEL SECURITY;
CREATE POLICY checkpoint_item_workspace_isolation ON checkpoint_item USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE conflict (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_a uuid NOT NULL,
  item_b uuid NOT NULL,
  detected_at timestamp with time zone DEFAULT now() NOT NULL,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  resolution conflict_resolution
);
ALTER TABLE conflict ADD CONSTRAINT conflict_items_distinct CHECK ((item_a <> item_b));
ALTER TABLE conflict ADD CONSTRAINT conflict_pkey PRIMARY KEY (id);
ALTER TABLE conflict ADD CONSTRAINT conflict_resolution_is_whole CHECK ((((resolved_at IS NULL) AND (resolved_by IS NULL) AND (resolution IS NULL)) OR ((resolved_at IS NOT NULL) AND (resolved_by IS NOT NULL) AND (resolution IS NOT NULL))));
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_item_a_fkey FOREIGN KEY (workspace_id, item_a) REFERENCES context_item(workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_item_b_fkey FOREIGN KEY (workspace_id, item_b) REFERENCES context_item(workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_resolved_by_fkey FOREIGN KEY (workspace_id, resolved_by) REFERENCES actor(workspace_id, id);
CREATE UNIQUE INDEX conflict_open_pair_unique ON public.conflict USING btree (workspace_id, project_id, LEAST(item_a, item_b), GREATEST(item_a, item_b)) WHERE (resolved_at IS NULL);
CREATE INDEX conflict_workspace_id_item_a_idx ON public.conflict USING btree (workspace_id, item_a);
CREATE INDEX conflict_workspace_id_item_b_idx ON public.conflict USING btree (workspace_id, item_b);
CREATE INDEX conflict_workspace_id_project_id_detected_at_idx ON public.conflict USING btree (workspace_id, project_id, detected_at DESC) WHERE (resolved_at IS NULL);
ALTER TABLE conflict ENABLE ROW LEVEL SECURITY;
ALTER TABLE conflict FORCE ROW LEVEL SECURITY;
CREATE POLICY conflict_workspace_isolation ON conflict USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE context_item (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  kind item_kind NOT NULL,
  title text NOT NULL,
  body text,
  status item_status DEFAULT 'active'::item_status NOT NULL,
  asserted_by uuid NOT NULL,
  asserted_at timestamp with time zone DEFAULT now() NOT NULL,
  source_session_id uuid,
  source_ref text,
  confidence real DEFAULT 0.5 NOT NULL,
  human_confirmed boolean DEFAULT false NOT NULL,
  load_bearing boolean DEFAULT false NOT NULL,
  last_verified_at timestamp with time zone,
  decay_after interval,
  valid_from timestamp with time zone DEFAULT now() NOT NULL,
  valid_to timestamp with time zone,
  supersedes_id uuid,
  superseded_by_id uuid,
  access_scope access_scope DEFAULT 'project'::access_scope NOT NULL,
  embedding vector(1536)
);
ALTER TABLE context_item ADD CONSTRAINT context_item_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)));
ALTER TABLE context_item ADD CONSTRAINT context_item_pkey PRIMARY KEY (id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_asserted_by_fkey FOREIGN KEY (workspace_id, asserted_by) REFERENCES actor(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_source_session_id_fkey FOREIGN KEY (workspace_id, source_session_id) REFERENCES session(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_superseded_by_id_fkey FOREIGN KEY (workspace_id, superseded_by_id) REFERENCES context_item(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_supersedes_id_fkey FOREIGN KEY (workspace_id, supersedes_id) REFERENCES context_item(workspace_id, id);
CREATE INDEX context_item_embedding_idx ON public.context_item USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX context_item_project_id_status_kind_idx ON public.context_item USING btree (project_id, status, kind);
ALTER TABLE context_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE context_item FORCE ROW LEVEL SECURITY;
CREATE POLICY context_item_workspace_isolation ON context_item USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE handoff (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  from_actor uuid NOT NULL,
  to_actor uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  received_at timestamp with time zone,
  next_action text NOT NULL,
  rendered text NOT NULL
);
ALTER TABLE handoff ADD CONSTRAINT handoff_pkey PRIMARY KEY (id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_from_actor_fkey FOREIGN KEY (workspace_id, from_actor) REFERENCES actor(workspace_id, id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_to_actor_fkey FOREIGN KEY (workspace_id, to_actor) REFERENCES actor(workspace_id, id);
CREATE INDEX handoff_workspace_id_project_id_idx ON public.handoff USING btree (workspace_id, project_id);
CREATE INDEX handoff_workspace_id_to_actor_idx ON public.handoff USING btree (workspace_id, to_actor) WHERE (received_at IS NULL);
ALTER TABLE handoff ENABLE ROW LEVEL SECURITY;
ALTER TABLE handoff FORCE ROW LEVEL SECURITY;
CREATE POLICY handoff_workspace_isolation ON handoff USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE mneia_schema_migration (
  version integer NOT NULL,
  name text NOT NULL,
  checksum text NOT NULL,
  applied_at timestamp with time zone DEFAULT now() NOT NULL,
  applied_by text
);
ALTER TABLE mneia_schema_migration ADD CONSTRAINT mneia_schema_migration_pkey PRIMARY KEY (version);

CREATE TABLE project (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  team_id uuid,
  slug text NOT NULL,
  repo_url text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  display_name text NOT NULL,
  archived_at timestamp with time zone
);
ALTER TABLE project ADD CONSTRAINT project_pkey PRIMARY KEY (id);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_slug_key UNIQUE (workspace_id, slug);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_team_id_fkey FOREIGN KEY (workspace_id, team_id) REFERENCES team(workspace_id, id);
CREATE INDEX project_active_workspace_display_name_idx ON public.project USING btree (workspace_id, display_name, id) WHERE (archived_at IS NULL);
CREATE INDEX project_workspace_id_team_id_idx ON public.project USING btree (workspace_id, team_id);
ALTER TABLE project ENABLE ROW LEVEL SECURITY;
ALTER TABLE project FORCE ROW LEVEL SECURITY;
CREATE POLICY project_workspace_isolation ON project USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE session (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  tool text,
  started_at timestamp with time zone NOT NULL,
  ended_at timestamp with time zone
);
ALTER TABLE session ADD CONSTRAINT session_pkey PRIMARY KEY (id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
CREATE INDEX session_workspace_id_actor_id_idx ON public.session USING btree (workspace_id, actor_id);
CREATE INDEX session_workspace_id_project_id_idx ON public.session USING btree (workspace_id, project_id);
ALTER TABLE session ENABLE ROW LEVEL SECURITY;
ALTER TABLE session FORCE ROW LEVEL SECURITY;
CREATE POLICY session_workspace_isolation ON session USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE team (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  slug text NOT NULL,
  display_name text NOT NULL,
  function team_function DEFAULT 'engineering'::team_function NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE team ADD CONSTRAINT team_pkey PRIMARY KEY (id);
ALTER TABLE team ADD CONSTRAINT team_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE team ADD CONSTRAINT team_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE team ADD CONSTRAINT team_workspace_id_slug_key UNIQUE (workspace_id, slug);
ALTER TABLE team ENABLE ROW LEVEL SECURITY;
ALTER TABLE team FORCE ROW LEVEL SECURITY;
CREATE POLICY team_workspace_isolation ON team USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE team_member (
  workspace_id uuid NOT NULL,
  team_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  role team_role DEFAULT 'member'::team_role NOT NULL,
  added_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE team_member ADD CONSTRAINT team_member_pkey PRIMARY KEY (team_id, actor_id);
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_team_id_fkey FOREIGN KEY (workspace_id, team_id) REFERENCES team(workspace_id, id);
CREATE INDEX team_member_actor_id_idx ON public.team_member USING btree (actor_id);
ALTER TABLE team_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_member FORCE ROW LEVEL SECURITY;
CREATE POLICY team_member_workspace_isolation ON team_member USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE waitlist_broadcast_send (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  campaign text NOT NULL,
  signup_id uuid NOT NULL,
  status text DEFAULT 'claimed'::text NOT NULL,
  provider_id text,
  claimed_at timestamp with time zone DEFAULT now() NOT NULL,
  delivered_at timestamp with time zone
);
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_campaign_check CHECK ((campaign <> ''::text));
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_delivered_when_sent CHECK (((status = 'sent'::text) = (delivered_at IS NOT NULL)));
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_pkey PRIMARY KEY (id);
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_signup_id_fkey FOREIGN KEY (signup_id) REFERENCES waitlist_signup(id) ON DELETE CASCADE;
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_status_check CHECK ((status = ANY (ARRAY['claimed'::text, 'sent'::text, 'unknown'::text])));
CREATE UNIQUE INDEX waitlist_broadcast_send_campaign_signup_key ON public.waitlist_broadcast_send USING btree (campaign, signup_id);
CREATE INDEX waitlist_broadcast_send_unresolved_idx ON public.waitlist_broadcast_send USING btree (campaign, claimed_at) WHERE (status <> 'sent'::text);

CREATE TABLE waitlist_signup (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  source text DEFAULT 'site'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  notified_at timestamp with time zone,
  unsubscribe_token uuid DEFAULT gen_random_uuid() NOT NULL
);
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_email_check CHECK ((email <> ''::text));
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX waitlist_signup_email_key ON public.waitlist_signup USING btree (lower(email));
CREATE UNIQUE INDEX waitlist_signup_unsubscribe_token_key ON public.waitlist_signup USING btree (unsubscribe_token);

CREATE TABLE workspace (
  id uuid NOT NULL,
  slug text NOT NULL,
  display_name text NOT NULL,
  plan text DEFAULT 'solo'::text NOT NULL,
  billing_status text DEFAULT 'active'::text NOT NULL,
  billing_customer_ref text,
  seats_purchased integer,
  checkpoint_allowance integer,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE workspace ADD CONSTRAINT workspace_billing_status_check CHECK ((billing_status = ANY (ARRAY['active'::text, 'trialing'::text, 'past_due'::text, 'canceled'::text])));
ALTER TABLE workspace ADD CONSTRAINT workspace_checkpoint_allowance_check CHECK (((checkpoint_allowance IS NULL) OR (checkpoint_allowance >= 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_pkey PRIMARY KEY (id);
ALTER TABLE workspace ADD CONSTRAINT workspace_plan_check CHECK ((plan = ANY (ARRAY['solo'::text, 'team'::text, 'enterprise'::text])));
ALTER TABLE workspace ADD CONSTRAINT workspace_seats_purchased_check CHECK (((seats_purchased IS NULL) OR (seats_purchased > 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_slug_key UNIQUE (slug);
ALTER TABLE workspace ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_workspace_isolation ON workspace USING ((id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));
