-- Generated by `pnpm db:snapshot`. Do not edit by hand.
--
-- This is the schema the migrations add up to, checked in so a reviewer can
-- see the resulting shape rather than replaying every migration, and so CI
-- can fail when a migration lands without a regenerated snapshot.
--
-- schema version: 38

-- extensions

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- enum types

CREATE TYPE access_scope AS ENUM ('private', 'project', 'team', 'workspace', 'restricted');
CREATE TYPE actor_kind AS ENUM ('human', 'agent');
CREATE TYPE checkpoint_action AS ENUM ('created', 'updated', 'superseded', 'rejected');
CREATE TYPE checkpoint_review_state AS ENUM ('pending', 'reviewed', 'auto_accepted');
CREATE TYPE checkpoint_trigger AS ENUM ('task_boundary', 'day_boundary', 'manual', 'pre_compaction');
CREATE TYPE conflict_resolution AS ENUM ('a_wins', 'b_wins', 'merged', 'both_retired');
CREATE TYPE grantee_kind AS ENUM ('actor', 'team');
CREATE TYPE item_kind AS ENUM ('decision', 'constraint', 'open_question', 'fact', 'artifact_ref');
CREATE TYPE item_status AS ENUM ('active', 'superseded', 'disputed', 'retired');
CREATE TYPE team_function AS ENUM ('engineering', 'product', 'design', 'sales', 'marketing', 'support', 'success', 'operations', 'finance', 'other');
CREATE TYPE team_role AS ENUM ('lead', 'member');
CREATE TYPE workspace_role AS ENUM ('owner', 'admin', 'member');

-- tables

CREATE TABLE actor (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  kind actor_kind NOT NULL,
  display_name text NOT NULL,
  external_ref text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  identity_id uuid
);
ALTER TABLE actor ADD CONSTRAINT actor_created_at_not_null NOT NULL created_at;
ALTER TABLE actor ADD CONSTRAINT actor_display_name_not_null NOT NULL display_name;
ALTER TABLE actor ADD CONSTRAINT actor_id_not_null NOT NULL id;
ALTER TABLE actor ADD CONSTRAINT actor_identified_human_carries_an_identity CHECK (((kind <> 'human'::actor_kind) OR (external_ref IS NULL) OR (external_ref = ''::text) OR (identity_id IS NOT NULL)));
ALTER TABLE actor ADD CONSTRAINT actor_identity_belongs_to_humans CHECK (((kind = 'human'::actor_kind) OR (identity_id IS NULL)));
ALTER TABLE actor ADD CONSTRAINT actor_identity_id_fkey FOREIGN KEY (identity_id) REFERENCES identity(id);
ALTER TABLE actor ADD CONSTRAINT actor_kind_not_null NOT NULL kind;
ALTER TABLE actor ADD CONSTRAINT actor_pkey PRIMARY KEY (id);
ALTER TABLE actor ADD CONSTRAINT actor_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE actor ADD CONSTRAINT actor_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE actor ADD CONSTRAINT actor_workspace_id_not_null NOT NULL workspace_id;
CREATE UNIQUE INDEX actor_human_external_ref_unique ON public.actor USING btree (workspace_id, external_ref) WHERE ((external_ref IS NOT NULL) AND (kind = 'human'::actor_kind));
CREATE INDEX actor_identity_idx ON public.actor USING btree (identity_id) WHERE (identity_id IS NOT NULL);
ALTER TABLE actor ENABLE ROW LEVEL SECURITY;
ALTER TABLE actor FORCE ROW LEVEL SECURITY;
CREATE POLICY actor_identity_lookup ON actor FOR SELECT USING (((kind = 'human'::actor_kind) AND (external_ref = NULLIF(current_setting('mneia.identity_subject'::text, true), ''::text)) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY actor_workspace_isolation ON actor USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE api_token (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  token_hash text NOT NULL,
  label text DEFAULT ''::text NOT NULL,
  device_authorization_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  last_used_at timestamp with time zone,
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  scopes text[] DEFAULT ARRAY['*'::text] NOT NULL
);
ALTER TABLE api_token ADD CONSTRAINT api_token_actor_id_not_null NOT NULL actor_id;
ALTER TABLE api_token ADD CONSTRAINT api_token_created_at_not_null NOT NULL created_at;
ALTER TABLE api_token ADD CONSTRAINT api_token_device_authorization_id_fkey FOREIGN KEY (device_authorization_id) REFERENCES device_authorization(id);
ALTER TABLE api_token ADD CONSTRAINT api_token_id_not_null NOT NULL id;
ALTER TABLE api_token ADD CONSTRAINT api_token_label_not_null NOT NULL label;
ALTER TABLE api_token ADD CONSTRAINT api_token_pkey PRIMARY KEY (id);
ALTER TABLE api_token ADD CONSTRAINT api_token_scopes_are_not_empty CHECK (((cardinality(scopes) > 0) AND (array_position(scopes, NULL::text) IS NULL) AND (NOT (''::text = ANY (scopes)))));
ALTER TABLE api_token ADD CONSTRAINT api_token_scopes_not_null NOT NULL scopes;
ALTER TABLE api_token ADD CONSTRAINT api_token_token_hash_not_null NOT NULL token_hash;
ALTER TABLE api_token ADD CONSTRAINT api_token_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE api_token ADD CONSTRAINT api_token_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE api_token ADD CONSTRAINT api_token_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE api_token ADD CONSTRAINT api_token_workspace_id_not_null NOT NULL workspace_id;
CREATE UNIQUE INDEX api_token_token_hash_key ON public.api_token USING btree (token_hash);
CREATE INDEX api_token_workspace_actor_idx ON public.api_token USING btree (workspace_id, actor_id, created_at DESC);
ALTER TABLE api_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_token FORCE ROW LEVEL SECURITY;
CREATE POLICY api_token_bearer_lookup ON api_token FOR SELECT USING (((token_hash = NULLIF(current_setting('mneia.api_token_hash'::text, true), ''::text)) AND (revoked_at IS NULL) AND ((expires_at IS NULL) OR (expires_at > now())) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY api_token_workspace_isolation ON api_token USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE audit_event (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  actor_id uuid,
  action text NOT NULL,
  target_kind text NOT NULL,
  target_id uuid,
  occurred_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);
ALTER TABLE audit_event ADD CONSTRAINT audit_event_action_is_not_blank CHECK ((action <> ''::text));
ALTER TABLE audit_event ADD CONSTRAINT audit_event_action_not_null NOT NULL action;
ALTER TABLE audit_event ADD CONSTRAINT audit_event_id_not_null NOT NULL id;
ALTER TABLE audit_event ADD CONSTRAINT audit_event_metadata_is_an_object CHECK ((jsonb_typeof(metadata) = 'object'::text));
ALTER TABLE audit_event ADD CONSTRAINT audit_event_metadata_not_null NOT NULL metadata;
ALTER TABLE audit_event ADD CONSTRAINT audit_event_occurred_at_not_null NOT NULL occurred_at;
ALTER TABLE audit_event ADD CONSTRAINT audit_event_pkey PRIMARY KEY (id);
ALTER TABLE audit_event ADD CONSTRAINT audit_event_target_kind_is_not_blank CHECK ((target_kind <> ''::text));
ALTER TABLE audit_event ADD CONSTRAINT audit_event_target_kind_not_null NOT NULL target_kind;
ALTER TABLE audit_event ADD CONSTRAINT audit_event_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE audit_event ADD CONSTRAINT audit_event_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE audit_event ADD CONSTRAINT audit_event_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX audit_event_target_idx ON public.audit_event USING btree (workspace_id, target_kind, target_id);
CREATE INDEX audit_event_workspace_idx ON public.audit_event USING btree (workspace_id, occurred_at DESC);
ALTER TABLE audit_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_event FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_event_workspace_isolation ON audit_event USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE checkpoint (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  session_id uuid,
  actor_id uuid NOT NULL,
  trigger checkpoint_trigger NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  summary text,
  review_state checkpoint_review_state DEFAULT 'pending'::checkpoint_review_state NOT NULL,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  extraction_model text,
  input_tokens integer,
  output_tokens integer,
  cost_micros bigint,
  extraction_duration_ms integer,
  source text,
  source_session_ref text,
  source_watermark text
);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_actor_id_not_null NOT NULL actor_id;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_created_at_not_null NOT NULL created_at;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_extraction_model_is_not_blank CHECK (((extraction_model IS NULL) OR (extraction_model <> ''::text)));
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_id_not_null NOT NULL id;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_pkey PRIMARY KEY (id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_project_id_not_null NOT NULL project_id;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_review_is_whole CHECK (((review_state = 'reviewed'::checkpoint_review_state) = ((reviewed_at IS NOT NULL) AND (reviewed_by IS NOT NULL))));
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_review_state_not_null NOT NULL review_state;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_source_fields_are_not_blank CHECK ((((source IS NULL) OR (source <> ''::text)) AND ((source_session_ref IS NULL) OR (source_session_ref <> ''::text)) AND ((source_watermark IS NULL) OR (source_watermark <> ''::text))));
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_source_watermark_needs_a_session CHECK (((source_watermark IS NULL) OR ((source IS NOT NULL) AND (source_session_ref IS NOT NULL))));
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_token_counts_are_not_negative CHECK ((((input_tokens IS NULL) OR (input_tokens >= 0)) AND ((output_tokens IS NULL) OR (output_tokens >= 0)) AND ((cost_micros IS NULL) OR (cost_micros >= 0)) AND ((extraction_duration_ms IS NULL) OR (extraction_duration_ms >= 0))));
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_trigger_not_null NOT NULL trigger;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_reviewed_by_fkey FOREIGN KEY (workspace_id, reviewed_by) REFERENCES actor(workspace_id, id);
ALTER TABLE checkpoint ADD CONSTRAINT checkpoint_workspace_id_session_id_fkey FOREIGN KEY (workspace_id, session_id) REFERENCES session(workspace_id, id);
CREATE INDEX checkpoint_pending_review_idx ON public.checkpoint USING btree (workspace_id, project_id, created_at DESC) WHERE (review_state = 'pending'::checkpoint_review_state);
CREATE INDEX checkpoint_source_resume_idx ON public.checkpoint USING btree (workspace_id, source, source_session_ref, created_at DESC) WHERE (source_session_ref IS NOT NULL);
CREATE INDEX checkpoint_workspace_id_project_id_created_at_idx ON public.checkpoint USING btree (workspace_id, project_id, created_at DESC);
CREATE INDEX checkpoint_workspace_id_session_id_idx ON public.checkpoint USING btree (workspace_id, session_id);
ALTER TABLE checkpoint ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint FORCE ROW LEVEL SECURITY;
CREATE POLICY checkpoint_workspace_isolation ON checkpoint USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE checkpoint_item (
  workspace_id uuid NOT NULL,
  checkpoint_id uuid NOT NULL,
  item_id uuid NOT NULL,
  action checkpoint_action NOT NULL
);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_action_not_null NOT NULL action;
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_checkpoint_id_not_null NOT NULL checkpoint_id;
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_item_id_not_null NOT NULL item_id;
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_pkey PRIMARY KEY (checkpoint_id, item_id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_checkpoint_id_fkey FOREIGN KEY (workspace_id, checkpoint_id) REFERENCES checkpoint(workspace_id, id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_item_id_fkey FOREIGN KEY (workspace_id, item_id) REFERENCES context_item(workspace_id, id);
ALTER TABLE checkpoint_item ADD CONSTRAINT checkpoint_item_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX checkpoint_item_item_id_idx ON public.checkpoint_item USING btree (item_id);
ALTER TABLE checkpoint_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint_item FORCE ROW LEVEL SECURITY;
CREATE POLICY checkpoint_item_workspace_isolation ON checkpoint_item USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE checkpoint_usage (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  checkpoint_id uuid,
  model text NOT NULL,
  input_tokens integer NOT NULL,
  output_tokens integer NOT NULL,
  duration_ms integer NOT NULL,
  outcome text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  cost_micros bigint
);
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_cost_is_not_negative CHECK (((cost_micros IS NULL) OR (cost_micros >= 0)));
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_created_at_not_null NOT NULL created_at;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_duration_ms_not_null NOT NULL duration_ms;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_id_not_null NOT NULL id;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_input_tokens_not_null NOT NULL input_tokens;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_measurements_are_not_negative CHECK (((input_tokens >= 0) AND (output_tokens >= 0) AND (duration_ms >= 0)));
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_model_is_not_blank CHECK ((model <> ''::text));
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_model_not_null NOT NULL model;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_outcome_is_known CHECK ((outcome = ANY (ARRAY['succeeded'::text, 'failed'::text, 'fell_back'::text])));
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_outcome_not_null NOT NULL outcome;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_output_tokens_not_null NOT NULL output_tokens;
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_pkey PRIMARY KEY (id);
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_workspace_id_checkpoint_id_fkey FOREIGN KEY (workspace_id, checkpoint_id) REFERENCES checkpoint(workspace_id, id);
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE checkpoint_usage ADD CONSTRAINT checkpoint_usage_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX checkpoint_usage_cost_idx ON public.checkpoint_usage USING btree (workspace_id, created_at) INCLUDE (cost_micros) WHERE (cost_micros IS NOT NULL);
CREATE INDEX checkpoint_usage_metering_idx ON public.checkpoint_usage USING btree (workspace_id, created_at);
ALTER TABLE checkpoint_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint_usage FORCE ROW LEVEL SECURITY;
CREATE POLICY checkpoint_usage_workspace_isolation ON checkpoint_usage USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE conflict (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_a uuid NOT NULL,
  item_b uuid NOT NULL,
  detected_at timestamp with time zone DEFAULT now() NOT NULL,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  resolution conflict_resolution,
  rationale text
);
ALTER TABLE conflict ADD CONSTRAINT conflict_detected_at_not_null NOT NULL detected_at;
ALTER TABLE conflict ADD CONSTRAINT conflict_id_not_null NOT NULL id;
ALTER TABLE conflict ADD CONSTRAINT conflict_item_a_not_null NOT NULL item_a;
ALTER TABLE conflict ADD CONSTRAINT conflict_item_b_not_null NOT NULL item_b;
ALTER TABLE conflict ADD CONSTRAINT conflict_items_distinct CHECK ((item_a <> item_b));
ALTER TABLE conflict ADD CONSTRAINT conflict_pkey PRIMARY KEY (id);
ALTER TABLE conflict ADD CONSTRAINT conflict_project_id_not_null NOT NULL project_id;
ALTER TABLE conflict ADD CONSTRAINT conflict_resolution_is_whole CHECK ((((resolved_at IS NULL) AND (resolved_by IS NULL) AND (resolution IS NULL) AND (rationale IS NULL)) OR ((resolved_at IS NOT NULL) AND (resolved_by IS NOT NULL) AND (resolution IS NOT NULL) AND (rationale IS NOT NULL) AND (rationale <> ''::text))));
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_item_a_fkey FOREIGN KEY (workspace_id, item_a) REFERENCES context_item(workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_item_b_fkey FOREIGN KEY (workspace_id, item_b) REFERENCES context_item(workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE conflict ADD CONSTRAINT conflict_workspace_id_resolved_by_fkey FOREIGN KEY (workspace_id, resolved_by) REFERENCES actor(workspace_id, id);
CREATE UNIQUE INDEX conflict_open_pair_unique ON public.conflict USING btree (workspace_id, project_id, LEAST(item_a, item_b), GREATEST(item_a, item_b)) WHERE (resolved_at IS NULL);
CREATE INDEX conflict_workspace_id_item_a_idx ON public.conflict USING btree (workspace_id, item_a);
CREATE INDEX conflict_workspace_id_item_b_idx ON public.conflict USING btree (workspace_id, item_b);
CREATE INDEX conflict_workspace_id_project_id_detected_at_idx ON public.conflict USING btree (workspace_id, project_id, detected_at DESC) WHERE (resolved_at IS NULL);
ALTER TABLE conflict ENABLE ROW LEVEL SECURITY;
ALTER TABLE conflict FORCE ROW LEVEL SECURITY;
CREATE POLICY conflict_workspace_isolation ON conflict USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE context_item (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  kind item_kind NOT NULL,
  title text NOT NULL,
  body text,
  status item_status DEFAULT 'active'::item_status NOT NULL,
  asserted_by uuid NOT NULL,
  asserted_at timestamp with time zone DEFAULT now() NOT NULL,
  source_session_id uuid,
  source_ref text,
  confidence real DEFAULT 0.5 NOT NULL,
  human_confirmed boolean DEFAULT false NOT NULL,
  load_bearing boolean DEFAULT false NOT NULL,
  last_verified_at timestamp with time zone,
  decay_after interval,
  valid_from timestamp with time zone DEFAULT now() NOT NULL,
  valid_to timestamp with time zone,
  supersedes_id uuid,
  superseded_by_id uuid,
  access_scope access_scope DEFAULT 'project'::access_scope NOT NULL,
  supersede_reason text,
  purge_after timestamp with time zone
);
ALTER TABLE context_item ADD CONSTRAINT context_item_access_scope_not_null NOT NULL access_scope;
ALTER TABLE context_item ADD CONSTRAINT context_item_asserted_at_not_null NOT NULL asserted_at;
ALTER TABLE context_item ADD CONSTRAINT context_item_asserted_by_not_null NOT NULL asserted_by;
ALTER TABLE context_item ADD CONSTRAINT context_item_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)));
ALTER TABLE context_item ADD CONSTRAINT context_item_confidence_not_null NOT NULL confidence;
ALTER TABLE context_item ADD CONSTRAINT context_item_human_confirmed_not_null NOT NULL human_confirmed;
ALTER TABLE context_item ADD CONSTRAINT context_item_id_not_null NOT NULL id;
ALTER TABLE context_item ADD CONSTRAINT context_item_kind_not_null NOT NULL kind;
ALTER TABLE context_item ADD CONSTRAINT context_item_load_bearing_not_null NOT NULL load_bearing;
ALTER TABLE context_item ADD CONSTRAINT context_item_pkey PRIMARY KEY (id);
ALTER TABLE context_item ADD CONSTRAINT context_item_project_id_not_null NOT NULL project_id;
ALTER TABLE context_item ADD CONSTRAINT context_item_status_not_null NOT NULL status;
ALTER TABLE context_item ADD CONSTRAINT context_item_supersede_reason_needs_a_predecessor CHECK (((supersede_reason IS NULL) OR ((supersedes_id IS NOT NULL) AND (supersede_reason <> ''::text))));
ALTER TABLE context_item ADD CONSTRAINT context_item_title_not_null NOT NULL title;
ALTER TABLE context_item ADD CONSTRAINT context_item_valid_from_not_null NOT NULL valid_from;
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_asserted_by_fkey FOREIGN KEY (workspace_id, asserted_by) REFERENCES actor(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_source_session_id_fkey FOREIGN KEY (workspace_id, source_session_id) REFERENCES session(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_superseded_by_id_fkey FOREIGN KEY (workspace_id, superseded_by_id) REFERENCES context_item(workspace_id, id);
ALTER TABLE context_item ADD CONSTRAINT context_item_workspace_id_supersedes_id_fkey FOREIGN KEY (workspace_id, supersedes_id) REFERENCES context_item(workspace_id, id);
CREATE INDEX context_item_load_bearing_idx ON public.context_item USING btree (workspace_id, project_id) WHERE ((status = 'active'::item_status) AND load_bearing AND (valid_to IS NULL));
CREATE INDEX context_item_project_id_status_kind_idx ON public.context_item USING btree (project_id, status, kind);
CREATE INDEX context_item_purge_idx ON public.context_item USING btree (purge_after) WHERE (purge_after IS NOT NULL);
CREATE INDEX context_item_verification_due_idx ON public.context_item USING btree (workspace_id, project_id, COALESCE(last_verified_at, asserted_at)) WHERE ((status = 'active'::item_status) AND (valid_to IS NULL) AND (decay_after IS NOT NULL));
ALTER TABLE context_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE context_item FORCE ROW LEVEL SECURITY;
CREATE POLICY context_item_workspace_isolation ON context_item USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE context_item_embedding (
  workspace_id uuid NOT NULL,
  item_id uuid NOT NULL,
  model text NOT NULL,
  dim integer NOT NULL,
  embedding vector(1536) NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_created_at_not_null NOT NULL created_at;
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_dim_matches CHECK ((dim = 1536));
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_dim_not_null NOT NULL dim;
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_embedding_not_null NOT NULL embedding;
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_item_id_not_null NOT NULL item_id;
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_model_is_not_blank CHECK ((model <> ''::text));
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_model_not_null NOT NULL model;
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_pkey PRIMARY KEY (item_id, model);
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_workspace_id_item_id_fkey FOREIGN KEY (workspace_id, item_id) REFERENCES context_item(workspace_id, id) ON DELETE CASCADE;
ALTER TABLE context_item_embedding ADD CONSTRAINT context_item_embedding_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX context_item_embedding_vector_idx ON public.context_item_embedding USING hnsw (embedding vector_cosine_ops);
CREATE INDEX context_item_embedding_workspace_item_idx ON public.context_item_embedding USING btree (workspace_id, item_id);
ALTER TABLE context_item_embedding ENABLE ROW LEVEL SECURITY;
ALTER TABLE context_item_embedding FORCE ROW LEVEL SECURITY;
CREATE POLICY context_item_embedding_workspace_isolation ON context_item_embedding USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE context_item_grant (
  workspace_id uuid NOT NULL,
  item_id uuid NOT NULL,
  grantee_kind grantee_kind NOT NULL,
  grantee_id uuid NOT NULL,
  granted_by uuid NOT NULL,
  granted_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_granted_at_not_null NOT NULL granted_at;
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_granted_by_not_null NOT NULL granted_by;
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_grantee_id_not_null NOT NULL grantee_id;
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_grantee_kind_not_null NOT NULL grantee_kind;
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_item_id_not_null NOT NULL item_id;
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_pkey PRIMARY KEY (item_id, grantee_kind, grantee_id);
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_workspace_id_granted_by_fkey FOREIGN KEY (workspace_id, granted_by) REFERENCES actor(workspace_id, id);
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_workspace_id_item_id_fkey FOREIGN KEY (workspace_id, item_id) REFERENCES context_item(workspace_id, id) ON DELETE CASCADE;
ALTER TABLE context_item_grant ADD CONSTRAINT context_item_grant_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX context_item_grant_grantee_idx ON public.context_item_grant USING btree (workspace_id, grantee_kind, grantee_id);
ALTER TABLE context_item_grant ENABLE ROW LEVEL SECURITY;
ALTER TABLE context_item_grant FORCE ROW LEVEL SECURITY;
CREATE POLICY context_item_grant_workspace_isolation ON context_item_grant USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE device_approval_attempt (
  workspace_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  window_started_at timestamp with time zone DEFAULT now() NOT NULL,
  failed_attempts integer DEFAULT 0 NOT NULL
);
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_actor_id_not_null NOT NULL actor_id;
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_failed_attempts_check CHECK ((failed_attempts >= 0));
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_failed_attempts_not_null NOT NULL failed_attempts;
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_pkey PRIMARY KEY (workspace_id, actor_id);
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_window_started_at_not_null NOT NULL window_started_at;
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE device_approval_attempt ADD CONSTRAINT device_approval_attempt_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE device_approval_attempt ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_approval_attempt FORCE ROW LEVEL SECURITY;
CREATE POLICY device_approval_attempt_workspace_isolation ON device_approval_attempt USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE device_authorization (
  id uuid NOT NULL,
  device_code_hash text NOT NULL,
  user_code text NOT NULL,
  confirmation_code text NOT NULL,
  client_label text DEFAULT ''::text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  claimed_workspace_id uuid,
  claimed_actor_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  claimed_at timestamp with time zone,
  redeemed_at timestamp with time zone
);
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_claim_is_whole CHECK (((claimed_workspace_id IS NULL) = (claimed_actor_id IS NULL)));
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_claim_matches_status CHECK (((status = 'pending'::text) = (claimed_workspace_id IS NULL)));
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_claimed_at_matches_claim CHECK (((claimed_at IS NULL) = (claimed_workspace_id IS NULL)));
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_claimed_workspace_id_claimed_actor_id_fkey FOREIGN KEY (claimed_workspace_id, claimed_actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_claimed_workspace_id_fkey FOREIGN KEY (claimed_workspace_id) REFERENCES workspace(id);
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_client_label_not_null NOT NULL client_label;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_confirmation_code_not_null NOT NULL confirmation_code;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_created_at_not_null NOT NULL created_at;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_device_code_hash_not_null NOT NULL device_code_hash;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_expires_after_creation CHECK ((expires_at > created_at));
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_expires_at_not_null NOT NULL expires_at;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_id_not_null NOT NULL id;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_pkey PRIMARY KEY (id);
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_redeemed_at_matches_status CHECK (((status = 'redeemed'::text) = (redeemed_at IS NOT NULL)));
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'redeemed'::text])));
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_status_not_null NOT NULL status;
ALTER TABLE device_authorization ADD CONSTRAINT device_authorization_user_code_not_null NOT NULL user_code;
CREATE UNIQUE INDEX device_authorization_device_code_hash_key ON public.device_authorization USING btree (device_code_hash);
CREATE INDEX device_authorization_expiry_idx ON public.device_authorization USING btree (expires_at);
CREATE UNIQUE INDEX device_authorization_user_code_key ON public.device_authorization USING btree (user_code);
ALTER TABLE device_authorization ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_authorization FORCE ROW LEVEL SECURITY;
CREATE POLICY device_authorization_claim ON device_authorization FOR UPDATE USING (((user_code = NULLIF(current_setting('mneia.device_user_code'::text, true), ''::text)) AND (status = 'pending'::text) AND (claimed_workspace_id IS NULL) AND (expires_at > now()))) WITH CHECK (((status = ANY (ARRAY['approved'::text, 'denied'::text])) AND (user_code = NULLIF(current_setting('mneia.device_user_code'::text, true), ''::text)) AND (claimed_workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)));
CREATE POLICY device_authorization_poll ON device_authorization FOR SELECT USING (((device_code_hash = NULLIF(current_setting('mneia.device_code_hash'::text, true), ''::text)) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY device_authorization_redemption ON device_authorization FOR UPDATE USING (((device_code_hash = NULLIF(current_setting('mneia.device_code_hash'::text, true), ''::text)) AND (claimed_workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid) AND (status = 'approved'::text) AND (expires_at > now()))) WITH CHECK (((status = 'redeemed'::text) AND (claimed_workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)));
CREATE POLICY device_authorization_start ON device_authorization FOR INSERT WITH CHECK (((status = 'pending'::text) AND (claimed_workspace_id IS NULL) AND (claimed_actor_id IS NULL) AND (redeemed_at IS NULL) AND (device_code_hash = NULLIF(current_setting('mneia.device_code_hash'::text, true), ''::text)) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY device_authorization_user_code_lookup ON device_authorization FOR SELECT USING (((user_code = NULLIF(current_setting('mneia.device_user_code'::text, true), ''::text)) AND (status = 'pending'::text) AND (expires_at > now())));
CREATE POLICY device_authorization_workspace_isolation ON device_authorization FOR SELECT USING ((claimed_workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE handoff (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  from_actor uuid NOT NULL,
  to_actor uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  received_at timestamp with time zone,
  next_action text NOT NULL,
  rendered text NOT NULL
);
ALTER TABLE handoff ADD CONSTRAINT handoff_created_at_not_null NOT NULL created_at;
ALTER TABLE handoff ADD CONSTRAINT handoff_from_actor_not_null NOT NULL from_actor;
ALTER TABLE handoff ADD CONSTRAINT handoff_id_not_null NOT NULL id;
ALTER TABLE handoff ADD CONSTRAINT handoff_next_action_not_null NOT NULL next_action;
ALTER TABLE handoff ADD CONSTRAINT handoff_pkey PRIMARY KEY (id);
ALTER TABLE handoff ADD CONSTRAINT handoff_project_id_not_null NOT NULL project_id;
ALTER TABLE handoff ADD CONSTRAINT handoff_rendered_not_null NOT NULL rendered;
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_from_actor_fkey FOREIGN KEY (workspace_id, from_actor) REFERENCES actor(workspace_id, id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
ALTER TABLE handoff ADD CONSTRAINT handoff_workspace_id_to_actor_fkey FOREIGN KEY (workspace_id, to_actor) REFERENCES actor(workspace_id, id);
CREATE INDEX handoff_workspace_id_project_id_idx ON public.handoff USING btree (workspace_id, project_id);
CREATE INDEX handoff_workspace_id_to_actor_idx ON public.handoff USING btree (workspace_id, to_actor) WHERE (received_at IS NULL);
ALTER TABLE handoff ENABLE ROW LEVEL SECURITY;
ALTER TABLE handoff FORCE ROW LEVEL SECURITY;
CREATE POLICY handoff_workspace_isolation ON handoff USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE handoff_item (
  workspace_id uuid NOT NULL,
  handoff_id uuid NOT NULL,
  item_id uuid NOT NULL,
  section text NOT NULL
);
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_handoff_id_not_null NOT NULL handoff_id;
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_item_id_not_null NOT NULL item_id;
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_pkey PRIMARY KEY (handoff_id, item_id);
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_section_is_not_blank CHECK ((section <> ''::text));
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_section_not_null NOT NULL section;
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_workspace_id_handoff_id_fkey FOREIGN KEY (workspace_id, handoff_id) REFERENCES handoff(workspace_id, id) ON DELETE CASCADE;
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_workspace_id_item_id_fkey FOREIGN KEY (workspace_id, item_id) REFERENCES context_item(workspace_id, id);
ALTER TABLE handoff_item ADD CONSTRAINT handoff_item_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX handoff_item_item_idx ON public.handoff_item USING btree (workspace_id, item_id);
ALTER TABLE handoff_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE handoff_item FORCE ROW LEVEL SECURITY;
CREATE POLICY handoff_item_workspace_isolation ON handoff_item USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE identity (
  id uuid NOT NULL,
  subject text NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE identity ADD CONSTRAINT identity_created_at_not_null NOT NULL created_at;
ALTER TABLE identity ADD CONSTRAINT identity_email_is_normalized CHECK (((email IS NULL) OR ((email = lower(btrim(email))) AND (POSITION(('@'::text) IN (email)) > 1))));
ALTER TABLE identity ADD CONSTRAINT identity_id_not_null NOT NULL id;
ALTER TABLE identity ADD CONSTRAINT identity_pkey PRIMARY KEY (id);
ALTER TABLE identity ADD CONSTRAINT identity_subject_is_not_blank CHECK ((subject <> ''::text));
ALTER TABLE identity ADD CONSTRAINT identity_subject_not_null NOT NULL subject;
CREATE UNIQUE INDEX identity_subject_key ON public.identity USING btree (subject);
ALTER TABLE identity ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity FORCE ROW LEVEL SECURITY;
CREATE POLICY identity_subject_enrolment ON identity FOR INSERT WITH CHECK ((subject = NULLIF(current_setting('mneia.identity_subject'::text, true), ''::text)));
CREATE POLICY identity_subject_lookup ON identity FOR SELECT USING ((subject = NULLIF(current_setting('mneia.identity_subject'::text, true), ''::text)));

CREATE TABLE mneia_schema_migration (
  version integer NOT NULL,
  name text NOT NULL,
  checksum text NOT NULL,
  applied_at timestamp with time zone DEFAULT now() NOT NULL,
  applied_by text
);
ALTER TABLE mneia_schema_migration ADD CONSTRAINT mneia_schema_migration_applied_at_not_null NOT NULL applied_at;
ALTER TABLE mneia_schema_migration ADD CONSTRAINT mneia_schema_migration_checksum_not_null NOT NULL checksum;
ALTER TABLE mneia_schema_migration ADD CONSTRAINT mneia_schema_migration_name_not_null NOT NULL name;
ALTER TABLE mneia_schema_migration ADD CONSTRAINT mneia_schema_migration_pkey PRIMARY KEY (version);
ALTER TABLE mneia_schema_migration ADD CONSTRAINT mneia_schema_migration_version_not_null NOT NULL version;

CREATE TABLE oauth_authorization_code (
  id uuid NOT NULL,
  code_hash text NOT NULL,
  client_id text NOT NULL,
  workspace_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  redirect_uri text NOT NULL,
  code_challenge text NOT NULL,
  code_challenge_method text DEFAULT 'S256'::text NOT NULL,
  resource text,
  scope text DEFAULT ''::text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  redeemed_at timestamp with time zone
);
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_actor_id_not_null NOT NULL actor_id;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_client_id_fkey FOREIGN KEY (client_id) REFERENCES oauth_client(client_id) ON DELETE CASCADE;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_client_id_not_null NOT NULL client_id;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_code_challenge_method_check CHECK ((code_challenge_method = 'S256'::text));
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_code_challenge_method_not_null NOT NULL code_challenge_method;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_code_challenge_not_null NOT NULL code_challenge;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_code_hash_not_null NOT NULL code_hash;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_created_at_not_null NOT NULL created_at;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_expires_after_creation CHECK ((expires_at > created_at));
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_expires_at_not_null NOT NULL expires_at;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_id_not_null NOT NULL id;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_pkey PRIMARY KEY (id);
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_redeemed_at_matches_status CHECK (((status = 'redeemed'::text) = (redeemed_at IS NOT NULL)));
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_redirect_uri_not_null NOT NULL redirect_uri;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_scope_not_null NOT NULL scope;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'redeemed'::text])));
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_status_not_null NOT NULL status;
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE oauth_authorization_code ADD CONSTRAINT oauth_authorization_code_workspace_id_not_null NOT NULL workspace_id;
CREATE UNIQUE INDEX oauth_authorization_code_code_hash_key ON public.oauth_authorization_code USING btree (code_hash);
CREATE INDEX oauth_authorization_code_expiry_idx ON public.oauth_authorization_code USING btree (expires_at);
ALTER TABLE oauth_authorization_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_authorization_code FORCE ROW LEVEL SECURITY;
CREATE POLICY oauth_authorization_code_issue ON oauth_authorization_code FOR INSERT WITH CHECK (((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid) AND (status = 'pending'::text) AND (redeemed_at IS NULL)));
CREATE POLICY oauth_authorization_code_redeem ON oauth_authorization_code FOR UPDATE USING (((code_hash = NULLIF(current_setting('mneia.oauth_code_hash'::text, true), ''::text)) AND (status = 'pending'::text) AND (expires_at > now()))) WITH CHECK (((code_hash = NULLIF(current_setting('mneia.oauth_code_hash'::text, true), ''::text)) AND (status = 'redeemed'::text)));
CREATE POLICY oauth_authorization_code_redeem_lookup ON oauth_authorization_code FOR SELECT USING (((code_hash = NULLIF(current_setting('mneia.oauth_code_hash'::text, true), ''::text)) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY oauth_authorization_code_workspace_isolation ON oauth_authorization_code FOR SELECT USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE oauth_client (
  id uuid NOT NULL,
  client_id text NOT NULL,
  client_secret_hash text,
  client_name text NOT NULL,
  redirect_uris text[] NOT NULL,
  grant_types text[] DEFAULT ARRAY['authorization_code'::text] NOT NULL,
  response_types text[] DEFAULT ARRAY['code'::text] NOT NULL,
  token_endpoint_auth_method text DEFAULT 'none'::text NOT NULL,
  application_type text DEFAULT 'native'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_application_type_check CHECK ((application_type = ANY (ARRAY['native'::text, 'web'::text])));
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_application_type_not_null NOT NULL application_type;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_client_id_not_null NOT NULL client_id;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_client_name_not_null NOT NULL client_name;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_created_at_not_null NOT NULL created_at;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_grant_types_not_null NOT NULL grant_types;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_has_redirect_uri CHECK ((cardinality(redirect_uris) > 0));
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_id_not_null NOT NULL id;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_pkey PRIMARY KEY (id);
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_redirect_uris_not_null NOT NULL redirect_uris;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_response_types_not_null NOT NULL response_types;
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_secret_matches_auth_method CHECK (((token_endpoint_auth_method = 'none'::text) = (client_secret_hash IS NULL)));
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_token_endpoint_auth_method_check CHECK ((token_endpoint_auth_method = ANY (ARRAY['none'::text, 'client_secret_post'::text, 'client_secret_basic'::text])));
ALTER TABLE oauth_client ADD CONSTRAINT oauth_client_token_endpoint_auth_method_not_null NOT NULL token_endpoint_auth_method;
CREATE UNIQUE INDEX oauth_client_client_id_key ON public.oauth_client USING btree (client_id);
ALTER TABLE oauth_client ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_client FORCE ROW LEVEL SECURITY;
CREATE POLICY oauth_client_lookup ON oauth_client FOR SELECT USING ((client_id = NULLIF(current_setting('mneia.oauth_client_id'::text, true), ''::text)));
CREATE POLICY oauth_client_register ON oauth_client FOR INSERT WITH CHECK ((NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL));

CREATE TABLE project (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  team_id uuid,
  slug text NOT NULL,
  repo_url text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  display_name text NOT NULL,
  archived_at timestamp with time zone
);
ALTER TABLE project ADD CONSTRAINT project_created_at_not_null NOT NULL created_at;
ALTER TABLE project ADD CONSTRAINT project_display_name_not_null NOT NULL display_name;
ALTER TABLE project ADD CONSTRAINT project_id_not_null NOT NULL id;
ALTER TABLE project ADD CONSTRAINT project_pkey PRIMARY KEY (id);
ALTER TABLE project ADD CONSTRAINT project_slug_not_null NOT NULL slug;
ALTER TABLE project ADD CONSTRAINT project_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE project ADD CONSTRAINT project_workspace_id_slug_key UNIQUE (workspace_id, slug);
ALTER TABLE project ADD CONSTRAINT project_workspace_id_team_id_fkey FOREIGN KEY (workspace_id, team_id) REFERENCES team(workspace_id, id);
CREATE INDEX project_active_workspace_display_name_idx ON public.project USING btree (workspace_id, display_name, id) WHERE (archived_at IS NULL);
CREATE INDEX project_workspace_id_team_id_idx ON public.project USING btree (workspace_id, team_id);
ALTER TABLE project ENABLE ROW LEVEL SECURITY;
ALTER TABLE project FORCE ROW LEVEL SECURITY;
CREATE POLICY project_workspace_isolation ON project USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE project_file_binding (
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  path text NOT NULL,
  fence_checksum text,
  last_imported_at timestamp with time zone,
  last_written_at timestamp with time zone
);
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_path_is_relative CHECK (((path <> ''::text) AND (path !~~ '/%'::text) AND (path !~~ '%..%'::text)));
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_path_not_null NOT NULL path;
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_pkey PRIMARY KEY (workspace_id, project_id, path);
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_project_id_not_null NOT NULL project_id;
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE project_file_binding ADD CONSTRAINT project_file_binding_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id) ON DELETE CASCADE;
ALTER TABLE project_file_binding ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_file_binding FORCE ROW LEVEL SECURITY;
CREATE POLICY project_file_binding_workspace_isolation ON project_file_binding USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE rate_limit_counter (
  workspace_id uuid NOT NULL,
  subject text NOT NULL,
  bucket text NOT NULL,
  window_start timestamp with time zone NOT NULL,
  count integer DEFAULT 0 NOT NULL
);
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_bucket_not_null NOT NULL bucket;
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_count_check CHECK ((count >= 0));
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_count_not_null NOT NULL count;
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_pkey PRIMARY KEY (workspace_id, subject, bucket, window_start);
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_subject_not_null NOT NULL subject;
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_window_start_not_null NOT NULL window_start;
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE;
ALTER TABLE rate_limit_counter ADD CONSTRAINT rate_limit_counter_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX rate_limit_counter_sweep_idx ON public.rate_limit_counter USING btree (workspace_id, window_start);
ALTER TABLE rate_limit_counter ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limit_counter FORCE ROW LEVEL SECURITY;
CREATE POLICY rate_limit_counter_workspace_isolation ON rate_limit_counter USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE session (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  tool text,
  started_at timestamp with time zone NOT NULL,
  ended_at timestamp with time zone,
  client_name text,
  client_version text,
  client_session_ref text,
  client_session_name text,
  client_session_url text,
  parent_session_id uuid
);
ALTER TABLE session ADD CONSTRAINT session_actor_id_not_null NOT NULL actor_id;
ALTER TABLE session ADD CONSTRAINT session_client_provenance_fields_are_not_blank CHECK ((((client_name IS NULL) OR (client_name <> ''::text)) AND ((client_version IS NULL) OR (client_version <> ''::text)) AND ((client_session_ref IS NULL) OR (client_session_ref <> ''::text)) AND ((client_session_name IS NULL) OR (client_session_name <> ''::text)) AND ((client_session_url IS NULL) OR (client_session_url <> ''::text))));
ALTER TABLE session ADD CONSTRAINT session_id_not_null NOT NULL id;
ALTER TABLE session ADD CONSTRAINT session_parent_session_id_is_not_self CHECK (((parent_session_id IS NULL) OR (parent_session_id <> id)));
ALTER TABLE session ADD CONSTRAINT session_pkey PRIMARY KEY (id);
ALTER TABLE session ADD CONSTRAINT session_project_id_not_null NOT NULL project_id;
ALTER TABLE session ADD CONSTRAINT session_started_at_not_null NOT NULL started_at;
ALTER TABLE session ADD CONSTRAINT session_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE session ADD CONSTRAINT session_workspace_id_parent_session_id_fkey FOREIGN KEY (workspace_id, parent_session_id) REFERENCES session(workspace_id, id);
ALTER TABLE session ADD CONSTRAINT session_workspace_id_project_id_fkey FOREIGN KEY (workspace_id, project_id) REFERENCES project(workspace_id, id);
CREATE INDEX session_workspace_id_actor_id_idx ON public.session USING btree (workspace_id, actor_id);
CREATE INDEX session_workspace_id_parent_session_id_idx ON public.session USING btree (workspace_id, parent_session_id) WHERE (parent_session_id IS NOT NULL);
CREATE INDEX session_workspace_id_project_id_client_session_ref_idx ON public.session USING btree (workspace_id, project_id, client_session_ref, started_at DESC) WHERE (client_session_ref IS NOT NULL);
CREATE INDEX session_workspace_id_project_id_idx ON public.session USING btree (workspace_id, project_id);
ALTER TABLE session ENABLE ROW LEVEL SECURITY;
ALTER TABLE session FORCE ROW LEVEL SECURITY;
CREATE POLICY session_workspace_isolation ON session USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE team (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  slug text NOT NULL,
  display_name text NOT NULL,
  function team_function DEFAULT 'engineering'::team_function NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE team ADD CONSTRAINT team_created_at_not_null NOT NULL created_at;
ALTER TABLE team ADD CONSTRAINT team_display_name_not_null NOT NULL display_name;
ALTER TABLE team ADD CONSTRAINT team_function_not_null NOT NULL function;
ALTER TABLE team ADD CONSTRAINT team_id_not_null NOT NULL id;
ALTER TABLE team ADD CONSTRAINT team_pkey PRIMARY KEY (id);
ALTER TABLE team ADD CONSTRAINT team_slug_not_null NOT NULL slug;
ALTER TABLE team ADD CONSTRAINT team_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE team ADD CONSTRAINT team_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE team ADD CONSTRAINT team_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE team ADD CONSTRAINT team_workspace_id_slug_key UNIQUE (workspace_id, slug);
ALTER TABLE team ENABLE ROW LEVEL SECURITY;
ALTER TABLE team FORCE ROW LEVEL SECURITY;
CREATE POLICY team_workspace_isolation ON team USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE team_member (
  workspace_id uuid NOT NULL,
  team_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  role team_role DEFAULT 'member'::team_role NOT NULL,
  added_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE team_member ADD CONSTRAINT team_member_actor_id_not_null NOT NULL actor_id;
ALTER TABLE team_member ADD CONSTRAINT team_member_added_at_not_null NOT NULL added_at;
ALTER TABLE team_member ADD CONSTRAINT team_member_pkey PRIMARY KEY (team_id, actor_id);
ALTER TABLE team_member ADD CONSTRAINT team_member_role_not_null NOT NULL role;
ALTER TABLE team_member ADD CONSTRAINT team_member_team_id_not_null NOT NULL team_id;
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_actor_id_fkey FOREIGN KEY (workspace_id, actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE team_member ADD CONSTRAINT team_member_workspace_id_team_id_fkey FOREIGN KEY (workspace_id, team_id) REFERENCES team(workspace_id, id);
CREATE INDEX team_member_actor_id_idx ON public.team_member USING btree (actor_id);
ALTER TABLE team_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_member FORCE ROW LEVEL SECURITY;
CREATE POLICY team_member_workspace_isolation ON team_member USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE telemetry_event (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  project_id uuid,
  actor_id uuid,
  session_id uuid,
  name text NOT NULL,
  occurred_at timestamp with time zone NOT NULL,
  recorded_at timestamp with time zone DEFAULT now() NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL
) PARTITION BY RANGE (occurred_at);
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_id_not_null NOT NULL id;
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_name_is_not_blank CHECK ((name <> ''::text));
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_name_not_null NOT NULL name;
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_occurred_at_not_null NOT NULL occurred_at;
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_payload_is_an_object CHECK ((jsonb_typeof(payload) = 'object'::text));
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_payload_not_null NOT NULL payload;
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_pkey PRIMARY KEY (id, occurred_at);
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_recorded_at_not_null NOT NULL recorded_at;
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE telemetry_event ADD CONSTRAINT telemetry_event_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX telemetry_event_metering_idx ON ONLY public.telemetry_event USING btree (workspace_id, name, occurred_at);
CREATE INDEX telemetry_event_project_idx ON ONLY public.telemetry_event USING btree (workspace_id, project_id, occurred_at);
ALTER TABLE telemetry_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry_event FORCE ROW LEVEL SECURITY;
CREATE POLICY telemetry_event_workspace_isolation ON telemetry_event USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE waitlist_broadcast_send (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  campaign text NOT NULL,
  signup_id uuid NOT NULL,
  status text DEFAULT 'claimed'::text NOT NULL,
  provider_id text,
  claimed_at timestamp with time zone DEFAULT now() NOT NULL,
  delivered_at timestamp with time zone
);
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_campaign_check CHECK ((campaign <> ''::text));
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_campaign_not_null NOT NULL campaign;
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_claimed_at_not_null NOT NULL claimed_at;
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_delivered_when_sent CHECK (((status = 'sent'::text) = (delivered_at IS NOT NULL)));
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_id_not_null NOT NULL id;
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_pkey PRIMARY KEY (id);
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_signup_id_fkey FOREIGN KEY (signup_id) REFERENCES waitlist_signup(id) ON DELETE CASCADE;
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_signup_id_not_null NOT NULL signup_id;
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_status_check CHECK ((status = ANY (ARRAY['claimed'::text, 'sent'::text, 'unknown'::text])));
ALTER TABLE waitlist_broadcast_send ADD CONSTRAINT waitlist_broadcast_send_status_not_null NOT NULL status;
CREATE UNIQUE INDEX waitlist_broadcast_send_campaign_signup_key ON public.waitlist_broadcast_send USING btree (campaign, signup_id);
CREATE INDEX waitlist_broadcast_send_unresolved_idx ON public.waitlist_broadcast_send USING btree (campaign, claimed_at) WHERE (status <> 'sent'::text);

CREATE TABLE waitlist_signup (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  source text DEFAULT 'site'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  notified_at timestamp with time zone,
  unsubscribe_token uuid DEFAULT gen_random_uuid() NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  approved_at timestamp with time zone,
  approved_by text,
  invitation_ref text
);
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_approval_is_attributed CHECK (((status = 'approved'::text) = ((approved_at IS NOT NULL) AND (approved_by IS NOT NULL))));
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_created_at_not_null NOT NULL created_at;
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_email_check CHECK ((email <> ''::text));
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_email_not_null NOT NULL email;
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_id_not_null NOT NULL id;
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_pkey PRIMARY KEY (id);
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_source_not_null NOT NULL source;
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text])));
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_status_not_null NOT NULL status;
ALTER TABLE waitlist_signup ADD CONSTRAINT waitlist_signup_unsubscribe_token_not_null NOT NULL unsubscribe_token;
CREATE UNIQUE INDEX waitlist_signup_email_key ON public.waitlist_signup USING btree (lower(email));
CREATE INDEX waitlist_signup_pending_idx ON public.waitlist_signup USING btree (created_at, id) WHERE (status = 'pending'::text);
CREATE INDEX waitlist_signup_purge_idx ON public.waitlist_signup USING btree (approved_at) WHERE (status = 'approved'::text);
CREATE UNIQUE INDEX waitlist_signup_unsubscribe_token_key ON public.waitlist_signup USING btree (unsubscribe_token);

CREATE TABLE wallet_ledger (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  kind text NOT NULL,
  amount_micros bigint NOT NULL,
  reason text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_amount_is_positive CHECK ((amount_micros > 0));
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_amount_micros_not_null NOT NULL amount_micros;
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_created_at_not_null NOT NULL created_at;
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_created_by_fkey FOREIGN KEY (workspace_id, created_by) REFERENCES actor(workspace_id, id);
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_id_not_null NOT NULL id;
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_kind_is_known CHECK ((kind = ANY (ARRAY['grant'::text, 'topup'::text, 'debit'::text])));
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_kind_not_null NOT NULL kind;
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_pkey PRIMARY KEY (workspace_id, id);
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_reason_is_not_blank CHECK ((reason <> ''::text));
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_reason_not_null NOT NULL reason;
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE;
ALTER TABLE wallet_ledger ADD CONSTRAINT wallet_ledger_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX wallet_ledger_workspace_history_idx ON public.wallet_ledger USING btree (workspace_id, created_at DESC);
ALTER TABLE wallet_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_ledger FORCE ROW LEVEL SECURITY;
CREATE POLICY wallet_ledger_workspace_isolation ON wallet_ledger USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE workspace (
  id uuid NOT NULL,
  slug text NOT NULL,
  display_name text NOT NULL,
  plan text DEFAULT 'solo'::text NOT NULL,
  billing_status text DEFAULT 'active'::text NOT NULL,
  billing_customer_ref text,
  seats_purchased integer,
  checkpoint_allowance integer,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  company_size text,
  retention_days integer,
  region text,
  turn_allowance bigint,
  extraction_allowance integer,
  embedding_token_allowance bigint,
  wallet_balance_micros bigint DEFAULT 0 NOT NULL,
  billing_subscription_ref text,
  billing_subscription_item_ref text
);
ALTER TABLE workspace ADD CONSTRAINT workspace_billing_status_check CHECK ((billing_status = ANY (ARRAY['active'::text, 'trialing'::text, 'past_due'::text, 'canceled'::text])));
ALTER TABLE workspace ADD CONSTRAINT workspace_billing_status_not_null NOT NULL billing_status;
ALTER TABLE workspace ADD CONSTRAINT workspace_billing_subscription_item_ref_is_not_blank CHECK (((billing_subscription_item_ref IS NULL) OR (billing_subscription_item_ref <> ''::text)));
ALTER TABLE workspace ADD CONSTRAINT workspace_billing_subscription_ref_is_not_blank CHECK (((billing_subscription_ref IS NULL) OR (billing_subscription_ref <> ''::text)));
ALTER TABLE workspace ADD CONSTRAINT workspace_checkpoint_allowance_check CHECK (((checkpoint_allowance IS NULL) OR (checkpoint_allowance >= 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_company_size_check CHECK (((company_size IS NULL) OR (company_size = ANY (ARRAY['1-9'::text, '10-49'::text, '50-199'::text, '200-499'::text, '500+'::text]))));
ALTER TABLE workspace ADD CONSTRAINT workspace_created_at_not_null NOT NULL created_at;
ALTER TABLE workspace ADD CONSTRAINT workspace_display_name_not_null NOT NULL display_name;
ALTER TABLE workspace ADD CONSTRAINT workspace_embedding_token_allowance_is_not_negative CHECK (((embedding_token_allowance IS NULL) OR (embedding_token_allowance >= 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_extraction_allowance_is_not_negative CHECK (((extraction_allowance IS NULL) OR (extraction_allowance >= 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_id_not_null NOT NULL id;
ALTER TABLE workspace ADD CONSTRAINT workspace_pkey PRIMARY KEY (id);
ALTER TABLE workspace ADD CONSTRAINT workspace_plan_check CHECK ((plan = ANY (ARRAY['solo'::text, 'pro'::text, 'team'::text, 'enterprise'::text])));
ALTER TABLE workspace ADD CONSTRAINT workspace_plan_not_null NOT NULL plan;
ALTER TABLE workspace ADD CONSTRAINT workspace_region_is_not_blank CHECK (((region IS NULL) OR (region <> ''::text)));
ALTER TABLE workspace ADD CONSTRAINT workspace_retention_days_is_positive CHECK (((retention_days IS NULL) OR (retention_days > 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_seats_purchased_check CHECK (((seats_purchased IS NULL) OR (seats_purchased > 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_slug_key UNIQUE (slug);
ALTER TABLE workspace ADD CONSTRAINT workspace_slug_not_null NOT NULL slug;
ALTER TABLE workspace ADD CONSTRAINT workspace_turn_allowance_is_not_negative CHECK (((turn_allowance IS NULL) OR (turn_allowance >= 0)));
ALTER TABLE workspace ADD CONSTRAINT workspace_wallet_balance_is_not_negative CHECK ((wallet_balance_micros >= 0));
ALTER TABLE workspace ADD CONSTRAINT workspace_wallet_balance_micros_not_null NOT NULL wallet_balance_micros;
ALTER TABLE workspace ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_workspace_isolation ON workspace USING ((id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE workspace_invitation (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  team_id uuid,
  invited_email text NOT NULL,
  token_hash text NOT NULL,
  role workspace_role DEFAULT 'member'::workspace_role NOT NULL,
  invited_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  accepted_actor_id uuid,
  revoked_at timestamp with time zone
);
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_acceptance_is_whole CHECK (((accepted_at IS NULL) = (accepted_actor_id IS NULL)));
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_created_at_not_null NOT NULL created_at;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_email_is_normalized CHECK (((invited_email = lower(btrim(invited_email))) AND (POSITION(('@'::text) IN (invited_email)) > 1)));
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_expires_after_creation CHECK ((expires_at > created_at));
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_expires_at_not_null NOT NULL expires_at;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_id_not_null NOT NULL id;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_invited_by_not_null NOT NULL invited_by;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_invited_email_not_null NOT NULL invited_email;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_is_not_both_accepted_and_revoked CHECK (((accepted_at IS NULL) OR (revoked_at IS NULL)));
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_pkey PRIMARY KEY (id);
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_role_not_null NOT NULL role;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_token_hash_not_null NOT NULL token_hash;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_workspace_id_accepted_actor_id_fkey FOREIGN KEY (workspace_id, accepted_actor_id) REFERENCES actor(workspace_id, id);
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_workspace_id_id_key UNIQUE (workspace_id, id);
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_workspace_id_invited_by_fkey FOREIGN KEY (workspace_id, invited_by) REFERENCES actor(workspace_id, id);
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE workspace_invitation ADD CONSTRAINT workspace_invitation_workspace_id_team_id_fkey FOREIGN KEY (workspace_id, team_id) REFERENCES team(workspace_id, id);
CREATE INDEX workspace_invitation_invited_email_idx ON public.workspace_invitation USING btree (invited_email) WHERE ((accepted_at IS NULL) AND (revoked_at IS NULL));
CREATE UNIQUE INDEX workspace_invitation_one_live_per_email ON public.workspace_invitation USING btree (workspace_id, invited_email) WHERE ((accepted_at IS NULL) AND (revoked_at IS NULL));
CREATE UNIQUE INDEX workspace_invitation_token_hash_key ON public.workspace_invitation USING btree (token_hash);
CREATE INDEX workspace_invitation_workspace_idx ON public.workspace_invitation USING btree (workspace_id, created_at DESC);
ALTER TABLE workspace_invitation ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_invitation FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_invitation_email_lookup ON workspace_invitation FOR SELECT USING (((invited_email = NULLIF(current_setting('mneia.invitation_email'::text, true), ''::text)) AND (accepted_at IS NULL) AND (revoked_at IS NULL) AND (expires_at > now()) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY workspace_invitation_token_lookup ON workspace_invitation FOR SELECT USING (((token_hash = NULLIF(current_setting('mneia.invitation_token_hash'::text, true), ''::text)) AND (accepted_at IS NULL) AND (revoked_at IS NULL) AND (expires_at > now()) AND (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL)));
CREATE POLICY workspace_invitation_workspace_isolation ON workspace_invitation USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE workspace_member (
  workspace_id uuid NOT NULL,
  identity_id uuid NOT NULL,
  role workspace_role DEFAULT 'member'::workspace_role NOT NULL,
  joined_at timestamp with time zone DEFAULT now() NOT NULL,
  invited_by uuid
);
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_identity_id_fkey FOREIGN KEY (identity_id) REFERENCES identity(id);
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_identity_id_not_null NOT NULL identity_id;
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES identity(id);
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_joined_at_not_null NOT NULL joined_at;
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_pkey PRIMARY KEY (workspace_id, identity_id);
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_role_not_null NOT NULL role;
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id);
ALTER TABLE workspace_member ADD CONSTRAINT workspace_member_workspace_id_not_null NOT NULL workspace_id;
CREATE INDEX workspace_member_identity_idx ON public.workspace_member USING btree (identity_id);
ALTER TABLE workspace_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_member FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_member_identity_lookup ON workspace_member FOR SELECT USING (((NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text) IS NULL) AND (EXISTS ( SELECT 1
   FROM identity
  WHERE ((identity.id = workspace_member.identity_id) AND (identity.subject = NULLIF(current_setting('mneia.identity_subject'::text, true), ''::text)))))));
CREATE POLICY workspace_member_workspace_isolation ON workspace_member USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));

CREATE TABLE workspace_usage_period (
  workspace_id uuid NOT NULL,
  period_start date NOT NULL,
  checkpoints_used integer DEFAULT 0 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  turns_used bigint DEFAULT 0 NOT NULL,
  extractions_used integer DEFAULT 0 NOT NULL,
  embedding_tokens_used bigint DEFAULT 0 NOT NULL
);
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_checkpoints_are_not_negative CHECK ((checkpoints_used >= 0));
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_checkpoints_used_not_null NOT NULL checkpoints_used;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_embedding_tokens_are_not_negative CHECK ((embedding_tokens_used >= 0));
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_embedding_tokens_used_not_null NOT NULL embedding_tokens_used;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_extractions_are_not_negative CHECK ((extractions_used >= 0));
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_extractions_used_not_null NOT NULL extractions_used;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_period_start_not_null NOT NULL period_start;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_pkey PRIMARY KEY (workspace_id, period_start);
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_starts_on_a_month CHECK ((period_start = (date_trunc('month'::text, (period_start)::timestamp with time zone))::date));
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_turns_are_not_negative CHECK ((turns_used >= 0));
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_turns_used_not_null NOT NULL turns_used;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_updated_at_not_null NOT NULL updated_at;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE;
ALTER TABLE workspace_usage_period ADD CONSTRAINT workspace_usage_period_workspace_id_not_null NOT NULL workspace_id;
ALTER TABLE workspace_usage_period ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_usage_period FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_usage_period_workspace_isolation ON workspace_usage_period USING ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid)) WITH CHECK ((workspace_id = (NULLIF(current_setting('mneia.workspace_id'::text, true), ''::text))::uuid));
